AY2324S2-CS2103T-T10-1/tp

docs/DeveloperGuide.md
Update Developer Guide
The developer guide has been updated to include use cases for copying emails.
This allows future developers to understand better how the 'copy' function interacts with users.
fixes #98
=> Update Developer Guide to include use cases for copying email addresses v1.1

docs/DeveloperGuide.md, docs/UserGuide.md
There is an overlapping usage for the term "parameter" which currently refers to both the prefixes "e/, n/, etc." and the user supplied input of "EMAIL, NAME, etc." which can cause confusion for users. The instructions for the find command are particularly confusing as it requires dynamic usage of prefixes.
Let's update the user guide to be clearer in explaining the usage of prefixes and parameters.
Fixes #128
=> Improve explaination for prefixes and find command in User Guide

docs/DeveloperGuide.md
edit,
* grammatical errors in case UC03
* formatting errors for extensions in UC03 to indicate where the use case resumes to after an extension case
=> fix: edit typo and formatting error in developer guide

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Person.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/model/person/PersonTest.java
initially the unique parameter of persons in the addressbook was the name of the person. however, it does not make sense for the name of the person to be unique as it is not uncommon for 2 persons in the cohort to have the same name. therefore, we changed the unique parameter to the email address of persons as 2 students in a cohort should not have the same email address.
change,
* method in Person class that compares two persons if they are equal to compare the email address of the persons instead of the name
* error message of the addressbook to warn users of a duplicate email address in a contact they attempt to add
fixes #95 
* change email address to be case-insensitive as john@example.com should be equal to John@example.com, so that two similar emails with different letter casing …
=> fix: change unique parameter of persons in the addressbook to email

build.gradle
(for week 10 tutorial)
Now, assertions are enabled on gradle and we are able to utilize this important tool to test developer assumptions.
Lets improve build process
=> Build: Enable Assertions

src/main/resources/view/MainWindow.fxml
Fixes #228 
Lock the size of exam list
Currently, the size of the exam list expands as the app size increases. Exam data should never be too long so it makes sense to lock the size of the exam list. So that the personslist can take up more space. This makes the UI look cleaner as well.
=> Lock size of exam list

src/main/java/seedu/address/logic/commands/AddScoreCommand.java, src/main/java/seedu/address/logic/commands/ImportExamCommand.java, src/main/java/seedu/address/logic/commands/SelectExamCommand.java, src/main/java/seedu/address/logic/parser/SelectExamCommandParser.java, src/test/java/seedu/address/logic/commands/AddScoreCommandTest.java, src/test/java/seedu/address/logic/commands/SelectExamCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/SelectExamCommandParserTest.java
SelectExamCommand currently uses names as a prefix to identify the exam to be selected. To make the application more user friendly, lets change the command to use exam indexes instead of names to identify the exam
Fixes #240
=> Change SelectExamCommand to use index instead of names

src/main/java/seedu/address/logic/Messages.java, src/main/resources/view/ExamListCard.fxml
Fix max_scores cutting off when having more than 5 digits.
Fix incorrect formatting of persons when printing in results after command execution.
Fixes #282
=> Update Spacing in UI and printing of persons

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/model/exam/Exam.java, src/main/java/seedu/address/model/person/Score.java, src/main/java/seedu/address/storage/JsonAdaptedExam.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/storage/JsonAdaptedExamTest.java
Currently, the AddCommandParser throws a very generic message when compulsory prefixes are missing from the user input. Lets change it so that it indicates which compulsory prefix is missing. This will also benefit the Import Command when it generates its error report.
Fixes #292
=> Modify AddCommand to throw more specfic exceptions

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/AutomaticTaggingActivityDiagram.puml, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Prevents feature flaw and minimizes false positives.
Now, auto tagging is solely based on the presence of matriculation number.
fixes #297 
1. Updated UG to reflect new behavior and emphasized the possibility of a student being a TA as well.
2. Modified unit tests.
=> Decrease overzealous autotag

src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/DeleteExamCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/ImportCommand.java, src/main/java/seedu/address/logic/commands/ImportExamScoresCommand.java, src/main/java/seedu/address/logic/commands/SelectExamCommand.java, src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Now the messages for commands are standardized.
Lets standardize messages.
1. Fixed erroneous success messages for importExamScores 
2. remove references to 'address book' because our product is much more than an address book. it is avengers assemble.
3. standardized capitalization for success messages
4. changed all references of `contact` to `person` instead
5. remove magic literal for `import` command
=> Fix: typos in success messages

src/main/java/seedu/address/model/ScoreStatistics.java, src/test/java/seedu/address/model/ScoreStatisticsTest.java
Currently, it is possible for the mean and median feature of the application to display numbers like these. Lets change it so that it is limited to 2 decimal places.
=> Limit Mean and Median to show 2DP

src/main/java/seedu/address/logic/commands/HelpCommand.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Now less mouse usage is required.
Lets optimize for typists.
=> Fix: remove pop up window for help command

src/main/java/seedu/address/MainApp.java
Now version is updated
Lets update version.
=> Build: update version number

docs/UserGuide.md
=> fix: typo in user guide

src/main/java/seedu/address/commons/util/CsvUtil.java, src/main/java/seedu/address/logic/commands/ImportCommand.java, src/main/java/seedu/address/logic/parser/ImportCommandParser.java, src/test/data/ImportCommandTest/duplicateHeaders.csv, src/test/java/seedu/address/commons/util/CsvUtilTest.java
Bug fix from PED
1) Now import Command properly displays its Usage message, with
a whitespace between import and i|
fixes #359 
2) ImportCommandParser now also checks for invalid characters in
filePath which is already caught by the InvalidPathException in
java
fixes #345 
3) Bug fix for when csv file to be imported is empty
Currently the readCsvFile method in CsvUtil only checks if the values
are empty but not if the rows themselves are empty. Now, it is
handled by readCsvFile to return an empty nullableData and
empty report
fixes #348
4) Bug fix for duplicate headers when they have the same value
For the case of duplicate headers, there is a bug in which when
there are 2 email coloumns with the same value, the person is not
added to the addressBook. (As stated in the PE-D, issue #362). …
=> BugFix: Bug Fixes from PED

docs/DeveloperGuide.md, docs/diagrams/FindImplementationActivityDiagram.puml, docs/diagrams/FindImplementationFindByScoreActivityDiagram.puml, docs/diagrams/FindImplementationPredicateCreationSequenceDiagram.puml, docs/diagrams/FindImplementationSequenceDiagram.puml
Currently, the find implementation documented in the DG is outdated,
as it details the previous implementation before the restructuring.
Furthermore, the diagrams are no longer accurate with the addition of
the exam score compatible functionality not being represented.
We need to update this promptly since we want the developer guide
to accurately represent the most recent implementation to aid in the
future development of the application.
Let's update the find implementation details in the developer guide,
as well as the supporting diagrams.
By keeping the information up to date, developers will be able to
accurately understand the implementation of the find functionality.
Sequence Diagrams: 
Activity Diagrams:
=> docs: Update find implementation in the DG

docs/DeveloperGuide.md
Now these sections are consistent with the overall manual testing
format that we have chosen to follow.
Lets standardize documentation.
1. launch & exit
2. saving
3. add
4. edit 
5. delete
6. list
7. deleteShown
8. importExamScores
=> Reformat Manual Testing Section in DG to follow standard formatting

docs/DeveloperGuide.md
fix small grammatical error in manual testing section for export
=> fix: typo in developer guide

docs/DeveloperGuide.md
Currently, some parts are phrased in a way that can be ambiguously
interpreted.
This needs to change because it makes the manual testing section
unclear.
Let's alter the manual testing section to remove any source of
ambiguity.
In doing so, we can ensure that the DG remains clear.
=> Minor Change to Manual Testing in DG
