docs/AboutUs.md
=> Update AboutUs.md for James Castillo

docs/AboutUs.md
=> Update AboutUs.md for Danielle

docs/DeveloperGuide.md
fixes #80 and #82
This allows developers to keep up to date and have our information in one place.
Lets improve documentation.
=> Update DeveloperGuide.md: insert the base information into the docs.

docs/UserGuide.md
=> docs: update user guide to support additional parameter

docs/UserGuide.md
Add a new command import that includes feature to import contacts from a csv file
=> Branch update user guide.md import feature

docs/DeveloperGuide.md
to fit more closely with functionalities.
This brings the developer guide closer to the actual implementation of the code.
Lets strive to improve documentation.
=> docs: improve phrasing of developer guide

build.gradle, docs/UserGuide.md, docs/tutorials/AddRemark.md, src/main/java/seedu/address/model/UserPrefs.java, src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json, src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
fixes #131 
This ensures consistency with our application, now named avengers assemble (AA). This removes any ambiguity or confusion by the reader.
Lets strive toward better documentation
=> fix: remove traces of AB3, replace with avengers assemble (AA)

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/matric/Matric.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/matric/MatricTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
fixes #89 
fixes #134 
Added an optional matriculation number encapsulated with the Matric class.
=> feat: add matriculation number param

.gitignore
Now, changes to local csv data are ignored and do not need to be pushed onto the repository.
Lets go la
=> build: update .gitignore to ignore addressbookdata directory.

docs/DeveloperGuide.md, docs/diagrams/AddSequenceDiagram.puml, docs/index.md
Now a more detailed sequence diagram is available for readers to understand the inner workings of a non-trivial command.
Lets strive to improve documentation.
=> docs: create a sequence diagram for the `add` command.

src/main/java/seedu/address/logic/commands/ImportCommand.java
Message_Usage editted to add newline character
=> Import command message_usage editted

src/main/java/seedu/address/MainApp.java
Now we reflect the correct updated version number.
Lets update the correct version number.
=> Update MainApp to reflect correct version number

docs/UserGuide.md
=> Update find command and Remove redundant AA references in User Guide

docs/DeveloperGuide.md, docs/diagrams/AddCommandParsing.puml, docs/diagrams/AddSequenceDiagram.puml
Now the sequence diagrams are in a better flow. Also extracted a reference frame to enhance readability.
Lets improve documentation
=> Docs update sequence of sequence diagrams

src/main/java/seedu/address/logic/commands/AddExamCommand.java, src/main/java/seedu/address/logic/commands/AddScoreCommand.java, src/main/java/seedu/address/logic/parser/AddExamCommandParser.java, src/main/java/seedu/address/logic/parser/EditExamCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/SelectExamCommandParser.java, src/main/java/seedu/address/model/exam/Exam.java, src/main/java/seedu/address/model/exam/UniqueExamList.java, src/test/java/seedu/address/logic/commands/AddScoreCommandTest.java, src/test/java/seedu/address/logic/parser/AddExamCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddScoreCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteExamCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditExamCommandParserTest.java, src/test/java/seedu/address/logic/parser/SelectExamCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/exam/ExamTest.java, src/test/java/seedu/address/model/exam/UniqueExamListTest.java, src/test/java/seedu/address/model/person/ScoreTest.java
Currently, the code coverage for the exams and scores commands is abysmal. Lets add tests to improve code coverage for that portion of the code. 
Fixes #233 
Fixes #232
=> Add unit tests for exams and scores and Fix bugs

src/main/java/seedu/address/ui/ExamCard.java, src/main/java/seedu/address/ui/ExamListPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/resources/view/PersonListCard.fxml
Add Updates to UI to make it more user friendly
1. Add exam highlight in GUI when exam is selected. User now can easily tell which exam is selected.
2. Increase column width for classes (Studio/Reflection). Width has been stretched to accomodate studio and reflection classes of up to 4 digits
3. Disable selecting items in GUI. User can no longer click on items in listview to select them. This prevents confusion in the selection of exams, since we have a CLI focused product. 
Fixes #253 
Fixes #251 
Fixes #231 
Let's continue to make our application more user friendly.
=> Feat: Update to UI

src/main/java/seedu/address/logic/commands/ImportExamCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/data/ImportExamCommandTest/testimportexamextra.csv, src/test/java/seedu/address/logic/commands/ImportExamCommandTest.java, src/test/java/seedu/address/logic/util/ModelStub.java, src/test/java/seedu/address/model/AddressBookTest.java
##Addition of utility functions for selecting objects by their unique parameter: 
1. Selecting exam by name
2. Selecting person by email
Now uses the more efficient, straightforward method to add exam score to person.
fixes #267 
Now, utility functions are utilized to make import exam command more efficient and less clunky.
Lets improve our code.
=> Refactor: Update implementation of import exam command

src/main/java/seedu/address/logic/commands/DeleteShownCommand.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Also refactored AddressBookParserTest to use constants instead of magic literals.
=> Fix: Rename deleteShown 

src/main/java/seedu/address/logic/commands/AddExamCommand.java, src/main/java/seedu/address/logic/commands/AddScoreCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/model/exam/Exam.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/ui/ExamListPanel.java, src/main/java/seedu/address/ui/NoSelectionModel.java, src/main/java/seedu/address/ui/PersonListPanel.java
Couple of bug fixes relating to input validation and UI
Fixes #367, fixes #366, fixes #365, fixes #364, fixes #346, fixes #344, fixes #363, fixes #358, fixes #355
=> Bug fixes for PE-D

src/main/java/seedu/address/logic/commands/ImportExamScoresCommand.java, src/main/java/seedu/address/model/exam/Exam.java, src/main/java/seedu/address/model/person/Name.java, src/test/java/seedu/address/logic/commands/ImportExamScoresCommandTest.java
1. Fixed importExamScores functionality and error reporting
2. Changed Name and Exam to allow for 1 char name
Fixes #369
Fixes #361
Fixes #360
Fixes #347
Fixes #333
Fixes #339
=> Fix ped bugs: Leng Khai

docs/DeveloperGuide.md, docs/diagrams/AddCommandParsing.puml, docs/diagrams/AddSequenceDiagram.puml, docs/diagrams/AutomaticTaggingActivityDiagram.puml, docs/diagrams/CopyImplementationActivityDiagram.puml, docs/diagrams/DeleteShownActivityDiagram.puml, docs/diagrams/EditCommandActivityDiagram.puml, docs/diagrams/FindImplementationActivityDiagram.puml, docs/diagrams/ImportExamScoresFileActivityDiagram.puml, docs/diagrams/style.puml, src/main/java/seedu/address/commons/util/CsvUtil.java, src/main/java/seedu/address/logic/parser/ImportExamScoresCommandParser.java, src/test/java/seedu/address/logic/parser/ImportExamScoresCommandParserTest.java
Features:
importExamScores
deleteShown
add
edit
delete
Manual testing
Launch & Shutdown
add
edit 
delete
deleteShown
list
importExamScores
planned enhancements
wrap text on result box so only 1 scrollbar needed
use both matric and email as primary key
make our sample data tags more relevant to head tutors
input validation for find command for prefixes other than lt and mt
=> Docs: Add assigned parts to DG

docs/DeveloperGuide.md
Currently, the implementation section of the DG is messy and the headers are not standardized in formatting. Lets update the implementation portion of the DG to make everything neater. 
This PR also adds additional information to the Effort section.
=> Format implementation section of DG

docs/diagrams/ImportParserSequenceDiagram.puml, docs/diagrams/ImportSequenceDiagram.puml
Here is the diagram with some changes. Since CsvUtil is from a different package, it is now placed in separate box and colour
=> Docs:Update sequence diagram for Import

docs/diagrams/AddSequenceDiagram.puml
Now the ref box is white in colour.
Lets keep diagrams consistent.
=> Fix the colouring of the ref box.

docs/DeveloperGuide.md
The parts that I have changed so far are:
- addExam
- selectExam
- deselectExam
- deleteExam
I also changed some usages of addressbook to avengers assemble
=> Reformatting manual testing section
